language: csharp
solution: TravisCITest.sln
dotnet: 1.1.5
install: 
  - nuget restore TravisCITest.sln
script: 
  - dotnet build
  - dotnet test TravisCITest_Tests/TravisCITest_Tests.csproj
notifications:
  email: false